// Code generated by tools/goextern; DO NOT EDIT.
// Source package: time
package goextern.time;

@:go.import("time")
@:go.package("time")
@:go.name("Duration")
@:go.valueType
extern class Duration {
	@:go.valueReturn
	@:go.name("Abs")
	public function abs():Duration;

	@:go.name("Hours")
	public function hours():Float;

	@:go.name("Microseconds")
	public function microseconds():Int;

	@:go.name("Milliseconds")
	public function milliseconds():Int;

	@:go.name("Minutes")
	public function minutes():Float;

	@:go.name("Nanoseconds")
	public function nanoseconds():Int;

	@:go.valueArgs("0")
	@:go.valueReturn
	@:go.name("Round")
	public function round(m:Duration):Duration;

	@:go.name("Seconds")
	public function seconds():Float;

	@:go.name("String")
	public function string():String;

	@:go.valueArgs("0")
	@:go.valueReturn
	@:go.name("Truncate")
	public function truncate(m:Duration):Duration;
}
