// Code generated by tools/goextern; DO NOT EDIT.
// Tuple carrier for Go multi-return extern calls.
package goextern.time;

/**
	What: typed Haxe carrier for a Go function that returns more than one value.
	Why: Haxe functions return one value, while Go can return multiple values directly.
	How: haxe.go lowers the matching `@:go.tupleReturn` extern call into this carrier.
**/
class LoadLocationFromTZDataResult {
	public var value1(default, null):Location;
	public var value2(default, null):Null<go.Error>;

	public function new(value1:Location, value2:Null<go.Error>) {
		this.value1 = value1;
		this.value2 = value2;
	}
}
