// Code generated by tools/goextern; DO NOT EDIT.
// Source package: time
package goextern.time;

@:go.import("time")
@:go.package("time")
@:go.name("Location")
@:go.struct
extern class Location {
	public function new();

	@:go.name("String")
	public function string():String;
}
