// Code generated by tools/goextern; DO NOT EDIT.
// Source package: time
package goextern.time;

@:go.import("time")
@:go.name("Location")
extern class Location {
	@:go.name("String")
	public function string():String;
}
