// Code generated by tools/goextern; DO NOT EDIT.
// Source package: time
package goextern.time;

@:go.import("time")
@:go.package("time")
@:go.name("Month")
extern class Month {
	@:go.name("String")
	public function string():String;
}
