// Code generated by tools/goextern; DO NOT EDIT.
// Source package: time
package goextern.time;

@:go.import("time")
@:go.name("ParseError")
extern class ParseError {
	@:go.name("Error")
	public function error():String;
}
