// Code generated by tools/goextern; DO NOT EDIT.
// Source package: time
package goextern.time;

@:go.import("time")
@:go.name("Ticker")
@:go.struct
extern class Ticker {
	public function new();

	@:go.name("Reset")
	public function reset(d:Duration):Void;

	@:go.name("Stop")
	public function stop():Void;
}
