// Code generated by tools/goextern; DO NOT EDIT.
// Tuple carrier for Go multi-return extern calls.
package goextern.time;

/**
	What: typed Haxe carrier for a Go function that returns more than one value.
	Why: Haxe functions return one value, while Go can return multiple values directly.
	How: haxe.go lowers the matching `@:go.tupleReturn` extern call into this carrier.
**/
class TimeZoneResult {
	public var name(default, null):String;
	public var offset(default, null):Int;

	public function new(name:String, offset:Int) {
		this.name = name;
		this.offset = offset;
	}
}
