// Code generated by tools/goextern; DO NOT EDIT.
// Source package: time
package goextern.time;

@:go.import("time")
@:go.name("Timer")
extern class Timer {
	@:go.name("Reset")
	public function reset(d:Duration):Bool;

	@:go.name("Stop")
	public function stop():Bool;
}
