// Code generated by tools/goextern; DO NOT EDIT.
// Tuple carrier for Go multi-return extern calls.
package goextern.time;

/**
	What: typed Haxe carrier for a Go function that returns more than one value.
	Why: Haxe functions return one value, while Go can return multiple values directly.
	How: haxe.go lowers the matching `@:go.tupleReturn` extern call into this carrier.
**/
class TimeDateResult {
	public var year(default, null):Int;
	public var month(default, null):Month;
	public var day(default, null):Int;

	public function new(year:Int, month:Month, day:Int) {
		this.year = year;
		this.month = month;
		this.day = day;
	}
}
