// Code generated by tools/goextern; DO NOT EDIT.
// Source package: time
package goextern.time;

@:go.import("time")
extern class TimePkg {
	@:go.name("After")
	public static function after(d:Duration):Dynamic;

	@:go.name("AfterFunc")
	public static function afterFunc(d:Duration, f:Dynamic):Timer;

	@:go.name("Date")
	public static function date(year:Int, month:Month, day:Int, hour:Int, min:Int, sec:Int, nsec:Int, loc:Location):Time;

	@:go.name("FixedZone")
	public static function fixedZone(name:String, offset:Int):Location;

	@:go.name("LoadLocation")
	public static function loadLocation(name:String):Dynamic;

	@:go.name("LoadLocationFromTZData")
	public static function loadLocationFromTZData(name:String, data:Array<Int>):Dynamic;

	@:go.name("NewTicker")
	public static function newTicker(d:Duration):Ticker;

	@:go.name("NewTimer")
	public static function newTimer(d:Duration):Timer;

	@:go.name("Now")
	public static function now():Time;

	@:go.name("Parse")
	public static function parse(layout:String, value:String):Dynamic;

	@:go.name("ParseDuration")
	public static function parseDuration(s:String):Dynamic;

	@:go.name("ParseInLocation")
	public static function parseInLocation(layout:String, value:String, loc:Location):Dynamic;

	@:go.name("Since")
	public static function since(t:Time):Duration;

	@:go.name("Sleep")
	public static function sleep(d:Duration):Void;

	@:go.name("Tick")
	public static function tick(d:Duration):Dynamic;

	@:go.name("Unix")
	public static function unix(sec:Int, nsec:Int):Time;

	@:go.name("UnixMicro")
	public static function unixMicro(usec:Int):Time;

	@:go.name("UnixMilli")
	public static function unixMilli(msec:Int):Time;

	@:go.name("Until")
	public static function until(t:Time):Duration;
}
