// Code generated by tools/goextern; DO NOT EDIT.
// Tuple carrier for Go multi-return extern calls.
package goextern.time;

/**
	What: typed Haxe carrier for a Go function that returns more than one value.
	Why: Haxe functions return one value, while Go can return multiple values directly.
	How: haxe.go lowers the matching `@:go.tupleReturn` extern call into this carrier.
**/
class TimeZoneBoundsResult {
	public var start(default, null):Time;
	public var end(default, null):Time;

	public function new(start:Time, end:Time) {
		this.start = start;
		this.end = end;
	}
}
