// Code generated by tools/goextern; DO NOT EDIT.
// Source package: time
package goextern.time;

@:go.import("time")
@:go.package("time")
@:go.name("Time")
@:go.struct
extern class Time {
	public function new();

	@:go.valueArgs("0")
	@:go.valueReturn
	@:go.name("Add")
	public function add(d:Duration):Time;

	@:go.valueReturn
	@:go.name("AddDate")
	public function addDate(years:Int, months:Int, days:Int):Time;

	@:go.valueArgs("0")
	@:go.name("After")
	public function after(u:Time):Bool;

	@:go.name("AppendFormat")
	public function appendFormat(b:go.NativeSlice<Int>, layout:String):go.NativeSlice<Int>;

	@:go.valueArgs("0")
	@:go.name("Before")
	public function before(u:Time):Bool;

	@:go.tupleReturn
	@:go.name("Clock")
	public function clock():TimeClockResult;

	@:go.valueArgs("0")
	@:go.name("Compare")
	public function compare(u:Time):Int;

	@:go.tupleReturn
	@:go.tupleValueResults("1")
	@:go.name("Date")
	public function date():TimeDateResult;

	@:go.name("Day")
	public function day():Int;

	@:go.valueArgs("0")
	@:go.name("Equal")
	public function equal(u:Time):Bool;

	@:go.name("Format")
	public function format(layout:String):String;

	@:go.name("GoString")
	public function goString():String;

	@:go.name("GobDecode")
	public function gobDecode(data:go.NativeSlice<Int>):go.Error;

	@:go.tupleReturn
	@:go.name("GobEncode")
	public function gobEncode():TimeGobEncodeResult;

	@:go.name("Hour")
	public function hour():Int;

	@:go.tupleReturn
	@:go.name("ISOWeek")
	public function iSOWeek():TimeISOWeekResult;

	@:go.valueReturn
	@:go.name("In")
	public function in_(loc:Location):Time;

	@:go.name("IsDST")
	public function isDST():Bool;

	@:go.name("IsZero")
	public function isZero():Bool;

	@:go.valueReturn
	@:go.name("Local")
	public function local():Time;

	@:go.name("Location")
	public function location():Location;

	@:go.tupleReturn
	@:go.name("MarshalBinary")
	public function marshalBinary():TimeMarshalBinaryResult;

	@:go.tupleReturn
	@:go.name("MarshalJSON")
	public function marshalJSON():TimeMarshalJSONResult;

	@:go.tupleReturn
	@:go.name("MarshalText")
	public function marshalText():TimeMarshalTextResult;

	@:go.name("Minute")
	public function minute():Int;

	@:go.valueReturn
	@:go.name("Month")
	public function month():Month;

	@:go.name("Nanosecond")
	public function nanosecond():Int;

	@:go.valueArgs("0")
	@:go.valueReturn
	@:go.name("Round")
	public function round(d:Duration):Time;

	@:go.name("Second")
	public function second():Int;

	@:go.name("String")
	public function string():String;

	@:go.valueArgs("0")
	@:go.valueReturn
	@:go.name("Sub")
	public function sub(u:Time):Duration;

	@:go.valueArgs("0")
	@:go.valueReturn
	@:go.name("Truncate")
	public function truncate(d:Duration):Time;

	@:go.valueReturn
	@:go.name("UTC")
	public function utc():Time;

	@:go.name("Unix")
	public function unix():Int;

	@:go.name("UnixMicro")
	public function unixMicro():Int;

	@:go.name("UnixMilli")
	public function unixMilli():Int;

	@:go.name("UnixNano")
	public function unixNano():Int;

	@:go.name("UnmarshalBinary")
	public function unmarshalBinary(data:go.NativeSlice<Int>):go.Error;

	@:go.name("UnmarshalJSON")
	public function unmarshalJSON(data:go.NativeSlice<Int>):go.Error;

	@:go.name("UnmarshalText")
	public function unmarshalText(data:go.NativeSlice<Int>):go.Error;

	@:go.valueReturn
	@:go.name("Weekday")
	public function weekday():Weekday;

	@:go.name("Year")
	public function year():Int;

	@:go.name("YearDay")
	public function yearDay():Int;

	@:go.tupleReturn
	@:go.name("Zone")
	public function zone():TimeZoneResult;

	@:go.tupleReturn
	@:go.tupleValueResults("0,1")
	@:go.name("ZoneBounds")
	public function zoneBounds():TimeZoneBoundsResult;
}
