// Code generated by tools/goextern; DO NOT EDIT.
// Tuple carrier for Go multi-return extern calls.
package goextern.time;

/**
	What: typed Haxe carrier for a Go function that returns more than one value.
	Why: Haxe functions return one value, while Go can return multiple values directly.
	How: haxe.go lowers the matching `@:go.tupleReturn` extern call into this carrier.
**/
class TimeClockResult {
	public var hour(default, null):Int;
	public var min(default, null):Int;
	public var sec(default, null):Int;

	public function new(hour:Int, min:Int, sec:Int) {
		this.hour = hour;
		this.min = min;
		this.sec = sec;
	}
}
