package hxrt.io;

import haxe.io.BytesData;

/**
	What: Typed access to native allocation and string/byte conversion primitives.

	Why: The mainstream `haxe.io.Bytes` implementation assumes target-specific
	byte storage. On `haxe.go`, public validation and algorithms belong in staged
	Haxe, but allocating `[]int` and converting through Go's UTF codecs are genuine
	runtime capabilities.

	How: Exchange only `BytesData`, strings, scalar policy flags, and opaque
	`ByteView` handles with `runtime/hxrt/bytes.go`. No generated Bytes layout or
	public IO policy crosses this boundary.
**/
@:go.import("hxrt")
@:go.package("hxrt")
extern class NativeBytes {
	@:go.name("BytesAllocValues")
	public static function allocValues(length:Int):BytesData;

	@:go.name("BytesViewFromValues")
	public static function viewFromValues(values:BytesData):ByteView;

	@:go.name("BytesViewFromString")
	public static function viewFromString(value:String, utf16LE:Bool):ByteView;

	@:go.name("BytesValuesFromView")
	public static function valuesFromView(view:ByteView):BytesData;

	@:go.name("BytesViewLength")
	public static function viewLength(view:ByteView):Int;

	@:go.name("BytesViewMatchesValues")
	public static function viewMatchesValues(view:ByteView, values:BytesData):Bool;

	@:go.name("BytesStringFromView")
	public static function stringFromView(view:ByteView, pos:Int, length:Int, utf16LE:Bool):String;

	@:go.name("BytesClone")
	public static function cloneValues(values:BytesData):BytesData;

	@:go.name("BytesBlitValues")
	public static function blitValues(target:BytesData, pos:Int, source:BytesData, sourcePos:Int, length:Int):Void;

	@:go.name("BytesBufferAddByte")
	public static function appendByte(values:BytesData, value:Int):BytesData;

	@:go.name("BytesBufferAdd")
	public static function appendValues(values:BytesData, source:BytesData):BytesData;

	@:go.name("BytesBufferAddSlice")
	public static function appendSlice(values:BytesData, source:BytesData, pos:Int, length:Int):BytesData;
}
