// Code generated by tools/goextern; DO NOT EDIT.
// Source package: context
package goextern.context;

@:go.import("context")
@:go.package("context")
@:go.name("CancelCauseFunc")
extern class CancelCauseFunc {}
