// Code generated by tools/goextern; DO NOT EDIT.
// Tuple carrier for Go multi-return extern calls.
package goextern.context;

/**
	What: typed Haxe carrier for a Go function that returns more than one value.
	Why: Haxe functions return one value, while Go can return multiple values directly.
	How: haxe.go lowers the matching `@:go.tupleReturn` extern call into this carrier.
**/
class ContextDeadlineResult {
	public var deadline(default, null):goextern.time.Time;
	public var ok(default, null):Bool;

	public function new(deadline:goextern.time.Time, ok:Bool) {
		this.deadline = deadline;
		this.ok = ok;
	}
}
