// Code generated by tools/goextern; DO NOT EDIT.
// Source package: context
package goextern.context;

@:go.import("context")
@:go.package("context")
extern class ContextPkg {
	@:go.name("AfterFunc")
	public static function afterFunc(ctx:Context, f:Dynamic):Dynamic;

	@:go.name("Background")
	public static function background():Context;

	@:go.name("Cause")
	public static function cause(c:Context):go.Error;

	@:go.name("TODO")
	public static function todo():Context;

	@:go.tupleReturn
	@:go.name("WithCancel")
	public static function withCancel(parent:Context):WithCancelResult;

	@:go.tupleReturn
	@:go.name("WithCancelCause")
	public static function withCancelCause(parent:Context):WithCancelCauseResult;

	@:go.tupleReturn
	@:go.name("WithDeadline")
	public static function withDeadline(parent:Context, d:goextern.time.Time):WithDeadlineResult;

	@:go.tupleReturn
	@:go.name("WithDeadlineCause")
	public static function withDeadlineCause(parent:Context, d:goextern.time.Time, cause:go.Error):WithDeadlineCauseResult;

	@:go.tupleReturn
	@:go.name("WithTimeout")
	public static function withTimeout(parent:Context, timeout:goextern.time.Duration):WithTimeoutResult;

	@:go.tupleReturn
	@:go.name("WithTimeoutCause")
	public static function withTimeoutCause(parent:Context, timeout:goextern.time.Duration, cause:go.Error):WithTimeoutCauseResult;

	@:go.name("WithValue")
	public static function withValue(parent:Context, key:Dynamic, val:Dynamic):Context;

	@:go.name("WithoutCancel")
	public static function withoutCancel(parent:Context):Context;
}
