// Code generated by tools/goextern; DO NOT EDIT.
// Source package: context
package goextern.context;

@:go.import("context")
@:go.package("context")
@:go.name("Context")
extern interface Context {
	@:go.tupleReturn
	@:go.name("Deadline")
	public function deadline():ContextDeadlineResult;

	@:go.name("Done")
	public function done():Dynamic;

	@:go.name("Err")
	public function err():go.Error;

	@:go.name("Value")
	public function value(key:Dynamic):Dynamic;
}
