// Code generated by tools/goextern; DO NOT EDIT.
// Tuple carrier for Go multi-return extern calls.
package goextern.context;

/**
	What: typed Haxe carrier for a Go function that returns more than one value.
	Why: Haxe functions return one value, while Go can return multiple values directly.
	How: haxe.go lowers the matching `@:go.tupleReturn` extern call into this carrier.
**/
class WithDeadlineResult {
	public var value1(default, null):Context;
	public var value2(default, null):CancelFunc;

	public function new(value1:Context, value2:CancelFunc) {
		this.value1 = value1;
		this.value2 = value2;
	}
}
