// Code generated by tools/goextern; DO NOT EDIT.
// Tuple carrier for Go multi-return extern calls.
package goextern.context;

/**
	What: typed Haxe carrier for a Go function that returns more than one value.
	Why: Haxe functions return one value, while Go can return multiple values directly.
	How: haxe.go lowers the matching `@:go.tupleReturn` extern call into this carrier.
**/
class WithCancelCauseResult {
	public var ctx(default, null):Context;
	public var cancel(default, null):CancelCauseFunc;

	public function new(ctx:Context, cancel:CancelCauseFunc) {
		this.ctx = ctx;
		this.cancel = cancel;
	}
}
