// Code generated by tools/goextern; DO NOT EDIT.
// Tuple carrier for Go multi-return extern calls.
package goextern.context;

/**
	What: typed Haxe carrier for a Go function that returns more than one value.
	Why: Haxe functions return one value, while Go can return multiple values directly.
	How: haxe.go lowers the matching `@:go.tupleReturn` extern call into this carrier.
**/
class WithCancelResult {
	public var ctx(default, null):Context;
	public var cancel(default, null):CancelFunc;

	public function new(ctx:Context, cancel:CancelFunc) {
		this.ctx = ctx;
		this.cancel = cancel;
	}
}
