// Code generated by tools/goextern; DO NOT EDIT.
// Source package: errors
package goextern.errors;

@:go.import("errors")
@:go.package("errors")
extern class ErrorsPkg {
	@:go.name("As")
	public static function as(err:go.Error, target:Dynamic):Bool;

	@:go.name("Is")
	public static function is(err:go.Error, target:go.Error):Bool;

	@:go.name("Join")
	public static function join(errs:haxe.Rest<go.Error>):go.Error;

	@:go.name("New")
	public static function new_(text:String):go.Error;

	@:go.name("Unwrap")
	public static function unwrap(err:go.Error):go.Error;
}
