/*
 * Copyright (C)2005-2019 Haxe Foundation
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

import hxrt.date.DateParts;
import hxrt.date.NativeDate;

/**
	What:
	- Implements the complete Haxe 4.3.7 `Date` API as staged source for the Go
	  target.

	Why:
	- The mainstream Haxe stdlib implementation cannot be used unchanged on
	  `haxe.go` because `Date` is an extern contract whose calendar and timezone
	  behavior must be supplied by each target.
	- Epoch-millisecond ownership, public constructors, and API policy are ordinary
	  Haxe behavior and must not be generated by `GoCompiler`.

	How:
	- Store the portable Haxe timestamp as a `Float` and delegate only host-local
	  calendar conversion, timezone lookup, parsing, formatting, and wall-clock
	  access through the typed `NativeDate` capability.
	- Keep generated `Date` objects out of `hxrt`; only scalars, strings, and the
	  runtime-owned `DateParts` carrier cross the package boundary.
**/
@:coreApi
class Date {
	private var ms:Float;

	public function new(year:Int, month:Int, day:Int, hour:Int, min:Int, sec:Int):Void {
		ms = NativeDate.localTime(year, month, day, hour, min, sec);
	}

	public inline function getTime():Float {
		return ms;
	}

	public function getHours():Int {
		return localParts().hours;
	}

	public function getMinutes():Int {
		return localParts().minutes;
	}

	public function getSeconds():Int {
		return localParts().seconds;
	}

	public function getFullYear():Int {
		return localParts().fullYear;
	}

	public function getMonth():Int {
		return localParts().month;
	}

	public function getDate():Int {
		return localParts().date;
	}

	public function getDay():Int {
		return localParts().day;
	}

	public function getUTCHours():Int {
		return utcParts().hours;
	}

	public function getUTCMinutes():Int {
		return utcParts().minutes;
	}

	public function getUTCSeconds():Int {
		return utcParts().seconds;
	}

	public function getUTCFullYear():Int {
		return utcParts().fullYear;
	}

	public function getUTCMonth():Int {
		return utcParts().month;
	}

	public function getUTCDate():Int {
		return utcParts().date;
	}

	public function getUTCDay():Int {
		return utcParts().day;
	}

	public function getTimezoneOffset():Int {
		return NativeDate.timezoneOffset(ms);
	}

	public function toString():String {
		return NativeDate.formatLocal(ms);
	}

	public static function now():Date {
		return fromMilliseconds(NativeDate.now());
	}

	public static function fromTime(t:Float):Date {
		return fromMilliseconds(t);
	}

	public static function fromString(s:String):Date {
		return fromMilliseconds(NativeDate.parse(s));
	}

	private inline function localParts():DateParts {
		return NativeDate.localParts(ms);
	}

	private inline function utcParts():DateParts {
		return NativeDate.utcParts(ms);
	}

	/**
		What:
		- Wraps an existing epoch-millisecond value in the staged `Date` layout.

		Why:
		- Haxe source has no constructor-bypassing allocation primitive, and exposing
		  the generated `Date` layout to `hxrt` would couple the runtime to compiler
		  output.

		How:
		- Construct one valid local placeholder, then replace only its private portable
		  timestamp before the value escapes.
	**/
	private static function fromMilliseconds(value:Float):Date {
		var result = new Date(1970, 0, 1, 0, 0, 0);
		result.ms = value;
		return result;
	}
}
