// Code generated by tools/goextern; DO NOT EDIT.
// Source package: sync
package goextern.sync;

@:go.import("sync")
@:go.name("Cond")
extern class Cond {
	@:go.name("Broadcast")
	public function broadcast():Void;

	@:go.name("Signal")
	public function signal():Void;

	@:go.name("Wait")
	public function wait():Void;
}
