// Code generated by tools/goextern; DO NOT EDIT.
// Source package: sync
package goextern.sync;

@:go.import("sync")
@:go.name("Cond")
@:go.struct
extern class Cond {
	public function new();

	@:go.name("L")
	public var l:Locker;

	@:go.name("Broadcast")
	public function broadcast():Void;

	@:go.name("Signal")
	public function signal():Void;

	@:go.name("Wait")
	public function wait():Void;
}
