// Code generated by tools/goextern; DO NOT EDIT.
// Source package: sync
package goextern.sync;

@:go.import("sync")
@:go.name("Locker")
extern interface Locker {
	@:go.name("Lock")
	public function lock():Void;

	@:go.name("Unlock")
	public function unlock():Void;
}
