// Code generated by tools/goextern; DO NOT EDIT.
// Source package: sync
package goextern.sync;

@:go.import("sync")
@:go.package("sync")
@:go.name("Map")
@:go.struct
extern class Map {
	public function new();

	@:go.name("Clear")
	public function clear():Void;

	@:go.name("CompareAndDelete")
	public function compareAndDelete(key:Dynamic, old:Dynamic):Bool;

	@:go.name("CompareAndSwap")
	public function compareAndSwap(key:Dynamic, old:Dynamic, new_:Dynamic):Bool;

	@:go.name("Delete")
	public function delete(key:Dynamic):Void;

	@:go.name("Load")
	public function load(key:Dynamic):Dynamic;

	@:go.name("LoadAndDelete")
	public function loadAndDelete(key:Dynamic):Dynamic;

	@:go.name("LoadOrStore")
	public function loadOrStore(key:Dynamic, value:Dynamic):Dynamic;

	@:go.name("Range")
	public function range(f:Dynamic):Void;

	@:go.name("Store")
	public function store(key:Dynamic, value:Dynamic):Void;

	@:go.name("Swap")
	public function swap(key:Dynamic, value:Dynamic):Dynamic;
}
