// Code generated by tools/goextern; DO NOT EDIT.
// Source package: sync
package goextern.sync;

@:go.import("sync")
@:go.name("Mutex")
@:go.struct
extern class Mutex {
	public function new();

	@:go.name("Lock")
	public function lock():Void;

	@:go.name("TryLock")
	public function tryLock():Bool;

	@:go.name("Unlock")
	public function unlock():Void;
}
