// Code generated by tools/goextern; DO NOT EDIT.
// Source package: sync
package goextern.sync;

@:go.import("sync")
@:go.package("sync")
@:go.name("Once")
@:go.struct
extern class Once {
	public function new();

	@:go.name("Do")
	public function do_(f:Dynamic):Void;
}
