// Code generated by tools/goextern; DO NOT EDIT.
// Source package: sync
package goextern.sync;

@:go.import("sync")
@:go.name("Once")
extern class Once {
	@:go.name("Do")
	public function do_(f:Dynamic):Void;
}
