// Code generated by tools/goextern; DO NOT EDIT.
// Source package: sync
package goextern.sync;

@:go.import("sync")
@:go.name("Pool")
extern class Pool {
	@:go.name("Get")
	public function get():Dynamic;

	@:go.name("Put")
	public function put(x:Dynamic):Void;
}
