// Code generated by tools/goextern; DO NOT EDIT.
// Source package: sync
package goextern.sync;

@:go.import("sync")
@:go.package("sync")
@:go.name("Pool")
@:go.struct
extern class Pool {
	public function new();

	@:go.name("Get")
	public function get():Dynamic;

	@:go.name("Put")
	public function put(x:Dynamic):Void;
}
