// Code generated by tools/goextern; DO NOT EDIT.
// Source package: sync
package goextern.sync;

@:go.import("sync")
@:go.package("sync")
@:go.name("RWMutex")
@:go.struct
extern class RWMutex {
	public function new();

	@:go.name("Lock")
	public function lock():Void;

	@:go.name("RLock")
	public function rLock():Void;

	@:go.name("RLocker")
	public function rLocker():Locker;

	@:go.name("RUnlock")
	public function rUnlock():Void;

	@:go.name("TryLock")
	public function tryLock():Bool;

	@:go.name("TryRLock")
	public function tryRLock():Bool;

	@:go.name("Unlock")
	public function unlock():Void;
}
