// Code generated by tools/goextern; DO NOT EDIT.
// Source package: sync
package goextern.sync;

@:go.import("sync")
extern class SyncPkg {
	@:go.name("NewCond")
	public static function newCond(l:Locker):Cond;

	@:go.name("OnceFunc")
	public static function onceFunc(f:Dynamic):Dynamic;

	@:go.name("OnceValue")
	public static function onceValue(f:Dynamic):Dynamic;

	@:go.name("OnceValues")
	public static function onceValues(f:Dynamic):Dynamic;
}
