// Code generated by tools/goextern; DO NOT EDIT.
// Source package: sync
package goextern.sync;

@:go.import("sync")
@:go.name("WaitGroup")
extern class WaitGroup {
	@:go.name("Add")
	public function add(delta:Int):Void;

	@:go.name("Done")
	public function done():Void;

	@:go.name("Go")
	public function go(f:Dynamic):Void;

	@:go.name("Wait")
	public function wait():Void;
}
