// Code generated by tools/goextern; DO NOT EDIT.
// Source package: io
package goextern.io;

@:go.import("io")
@:go.package("io")
@:go.name("Reader")
extern interface Reader {
	@:go.tupleReturn
	@:go.name("Read")
	public function read(p:go.NativeSlice<Int>):ReaderReadResult;
}
