// Code generated by tools/goextern; DO NOT EDIT.
// Source package: io
package goextern.io;

@:go.import("io")
@:go.package("io")
@:go.name("Writer")
extern interface Writer {
	@:go.tupleReturn
	@:go.name("Write")
	public function write(p:go.NativeSlice<Int>):WriterWriteResult;
}
