// Code generated by tools/goextern; DO NOT EDIT.
// Source package: fmt
package goextern.fmt;

@:go.import("fmt")
extern class FmtPkg {
	@:go.name("Append")
	public static function append(b:go.NativeSlice<Int>, a:haxe.Rest<Dynamic>):go.NativeSlice<Int>;

	@:go.name("Appendf")
	public static function appendf(b:go.NativeSlice<Int>, format:String, a:haxe.Rest<Dynamic>):go.NativeSlice<Int>;

	@:go.name("Appendln")
	public static function appendln(b:go.NativeSlice<Int>, a:haxe.Rest<Dynamic>):go.NativeSlice<Int>;

	@:go.name("Errorf")
	public static function errorf(format:String, a:haxe.Rest<Dynamic>):go.Error;

	@:go.name("FormatString")
	public static function formatString(state:State, verb:Int):String;

	@:go.tupleReturn
	@:go.name("Fprint")
	public static function fprint(w:Dynamic, a:haxe.Rest<Dynamic>):FprintResult;

	@:go.tupleReturn
	@:go.name("Fprintf")
	public static function fprintf(w:Dynamic, format:String, a:haxe.Rest<Dynamic>):FprintfResult;

	@:go.tupleReturn
	@:go.name("Fprintln")
	public static function fprintln(w:Dynamic, a:haxe.Rest<Dynamic>):FprintlnResult;

	@:go.tupleReturn
	@:go.name("Fscan")
	public static function fscan(r:Dynamic, a:haxe.Rest<Dynamic>):FscanResult;

	@:go.tupleReturn
	@:go.name("Fscanf")
	public static function fscanf(r:Dynamic, format:String, a:haxe.Rest<Dynamic>):FscanfResult;

	@:go.tupleReturn
	@:go.name("Fscanln")
	public static function fscanln(r:Dynamic, a:haxe.Rest<Dynamic>):FscanlnResult;

	@:go.tupleReturn
	@:go.name("Print")
	public static function print(a:haxe.Rest<Dynamic>):PrintResult;

	@:go.tupleReturn
	@:go.name("Printf")
	public static function printf(format:String, a:haxe.Rest<Dynamic>):PrintfResult;

	@:go.tupleReturn
	@:go.name("Println")
	public static function println(a:haxe.Rest<Dynamic>):PrintlnResult;

	@:go.tupleReturn
	@:go.name("Scan")
	public static function scan(a:haxe.Rest<Dynamic>):ScanResult;

	@:go.tupleReturn
	@:go.name("Scanf")
	public static function scanf(format:String, a:haxe.Rest<Dynamic>):ScanfResult;

	@:go.tupleReturn
	@:go.name("Scanln")
	public static function scanln(a:haxe.Rest<Dynamic>):ScanlnResult;

	@:go.name("Sprint")
	public static function sprint(a:haxe.Rest<Dynamic>):String;

	@:go.name("Sprintf")
	public static function sprintf(format:String, a:haxe.Rest<Dynamic>):String;

	@:go.name("Sprintln")
	public static function sprintln(a:haxe.Rest<Dynamic>):String;

	@:go.tupleReturn
	@:go.name("Sscan")
	public static function sscan(str:String, a:haxe.Rest<Dynamic>):SscanResult;

	@:go.tupleReturn
	@:go.name("Sscanf")
	public static function sscanf(str:String, format:String, a:haxe.Rest<Dynamic>):SscanfResult;

	@:go.tupleReturn
	@:go.name("Sscanln")
	public static function sscanln(str:String, a:haxe.Rest<Dynamic>):SscanlnResult;
}
