// Code generated by tools/goextern; DO NOT EDIT.
// Source package: fmt
package goextern.fmt;

@:go.import("fmt")
@:go.package("fmt")
@:go.name("Formatter")
extern interface Formatter {
	@:go.name("Format")
	public function format(f:State, verb:Int):Void;
}
