// Code generated by tools/goextern; DO NOT EDIT.
// Source package: fmt
package goextern.fmt;

@:go.import("fmt")
@:go.package("fmt")
@:go.name("GoStringer")
extern interface GoStringer {
	@:go.name("GoString")
	public function goString():String;
}
