// Code generated by tools/goextern; DO NOT EDIT.
// Tuple carrier for Go multi-return extern calls.
package goextern.fmt;

/**
	What: typed Haxe carrier for a Go function that returns more than one value.
	Why: Haxe functions return one value, while Go can return multiple values directly.
	How: haxe.go lowers the matching `@:go.tupleReturn` extern call into this carrier.
**/
class ScanStateReadRuneResult {
	public var r(default, null):Int;
	public var size(default, null):Int;
	public var err(default, null):Null<go.Error>;

	public function new(r:Int, size:Int, err:Null<go.Error>) {
		this.r = r;
		this.size = size;
		this.err = err;
	}
}
