// Code generated by tools/goextern; DO NOT EDIT.
// Source package: fmt
package goextern.fmt;

@:go.import("fmt")
@:go.package("fmt")
@:go.name("ScanState")
extern interface ScanState {
	@:go.tupleReturn
	@:go.name("Read")
	public function read(buf:go.NativeSlice<Int>):ScanStateReadResult;

	@:go.tupleReturn
	@:go.name("ReadRune")
	public function readRune():ScanStateReadRuneResult;

	@:go.name("SkipSpace")
	public function skipSpace():Void;

	@:go.tupleReturn
	@:go.name("Token")
	public function token(skipSpace:Bool, f:Dynamic):ScanStateTokenResult;

	@:go.name("UnreadRune")
	public function unreadRune():go.Error;

	@:go.tupleReturn
	@:go.name("Width")
	public function width():ScanStateWidthResult;
}
