// Code generated by tools/goextern; DO NOT EDIT.
// Source package: fmt
package goextern.fmt;

@:go.import("fmt")
@:go.package("fmt")
@:go.name("Scanner")
extern interface Scanner {
	@:go.name("Scan")
	public function scan(state:ScanState, verb:Int):go.Error;
}
