// Code generated by tools/goextern; DO NOT EDIT.
// Source package: fmt
package goextern.fmt;

@:go.import("fmt")
@:go.name("ScanState")
extern interface ScanState {
	@:go.name("Read")
	public function read(buf:Array<Int>):Dynamic;

	@:go.name("ReadRune")
	public function readRune():Dynamic;

	@:go.name("SkipSpace")
	public function skipSpace():Void;

	@:go.name("Token")
	public function token(skipSpace:Bool, f:Dynamic):Dynamic;

	@:go.name("UnreadRune")
	public function unreadRune():go.Error;

	@:go.name("Width")
	public function width():Dynamic;
}
