// Code generated by tools/goextern; DO NOT EDIT.
// Source package: fmt
package goextern.fmt;

@:go.import("fmt")
@:go.name("State")
extern interface State {
	@:go.name("Flag")
	public function flag(c:Int):Bool;

	@:go.name("Precision")
	public function precision():Dynamic;

	@:go.name("Width")
	public function width():Dynamic;

	@:go.name("Write")
	public function write(b:Array<Int>):Dynamic;
}
