// Code generated by tools/goextern; DO NOT EDIT.
// Tuple carrier for Go multi-return extern calls.
package goextern.fmt;

/**
	What: typed Haxe carrier for a Go function that returns more than one value.
	Why: Haxe functions return one value, while Go can return multiple values directly.
	How: haxe.go lowers the matching `@:go.tupleReturn` extern call into this carrier.
**/
class StatePrecisionResult {
	public var prec(default, null):Int;
	public var ok(default, null):Bool;

	public function new(prec:Int, ok:Bool) {
		this.prec = prec;
		this.ok = ok;
	}
}
