// Code generated by tools/goextern; DO NOT EDIT.
// Source package: fmt
package goextern.fmt;

@:go.import("fmt")
@:go.package("fmt")
@:go.name("Stringer")
extern interface Stringer {
	@:go.name("String")
	public function string():String;
}
